name = "dit-report"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "dit-report"
database_id = "2aa70294-3246-41fa-ae04-c396cdbc1335"

[browser]
binding = "BROWSER"
